[build-system]
requires = [
    "setuptools>=61.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]

[tool.setuptools.packages.find]
where = ["."]
include = ["vhrharmonize*"]

[tool.setuptools.package-data]
vhrharmonize = ["py.typed"]

[project]
name = "vhrharmonize"
version = "2.0.4"
description = "Automated open source library to preprocess satellite imagery"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Kanoa Lindiwe", email = "cankanoa@gmail.com"}
]
maintainers = [
    {name = "Joseph Emile Honour Percival", email = "ipercival@gmail.com"}
]
keywords = ['Remote sensing', 'Satellite imagery', 'Image preprocessing', 'Orthorectification', 'Pansharpening', 'Atmospheric correction', 'RPC refinement', 'WorldView', 'Python automation', 'Raster processing', 'Multispectral imagery']
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

dependencies = [
    "rasterio>=1.4.3",
    "tifffile",
    "numpy>=2.2",
    "geopandas>=1.0.1",
    "shapely>=2.1",
    "pyyaml",
    "jsonata-python>=0.7.0,<0.8",
    "requests>=2.32.3",
    "pyproj>=3.7",
    "tqdm",
    "rich>=13.7",
    "wcmatch>=10.0",
]

[project.optional-dependencies]
#dev = [
#    "pytest>=7.0.0",
#    "pytest-mock>=3.14.0",
#    "pytest-cov>=4.0.0",
#    "flake8>=6.0.0",
#    "black>=23.0.0",
#    "pre-commit>=4.1.0"
#]

system-level = [
    "gdal>=3.11",
    "sixs",
]

cloud = [
    "omnicloudmask",
    "scipy>=1.15",
    "imageio",
]

py6s = [
    "Py6S",
]

flaash = [
    "envipyengine>=1.0.9",
]

orthorectification = [
    "orthority>=0.5.1",
]

pansharpen = [
    "orthority>=0.5.1",
]

spectralmatch = [
    "spectralmatch>=1.6,<2"
]

align = [
    "coregix",
]

docs = [
    "mkdocs>=1.6,<2.0",
    "mkdocs-material>=9.0.0",
    "mkdocs-jupyter>=0.24.0",
    "mkdocstrings>=0.21.0",
    "mkdocstrings-python>=0.10.0",
    "mkdocs-git-revision-date-plugin>=0.3,<0.3.3",
    "pymdown-extensions>=9.10"
]

defaults = [
    "omnicloudmask",
    "scipy>=1.15",
    "imageio",
    "requests>=2.32.3",
    "Py6S",
    "orthority>=0.5.1",
    "spectralmatch>=1.6,<2",
    "coregix"
]

all = [
    "omnicloudmask",
    "scipy>=1.15",
    "imageio",
    "requests>=2.32.3",
    "Py6S",
    "envipyengine>=1.0.9",
    "orthority>=0.5.1",
    "spectralmatch>=1.6,<2",
    "coregix"
]

dask = [
    "dask[distributed]"
]

[project.urls]
"Bug Tracker" = "https://github.com/cankanoa/vhrharmonize/issues"
"Source" = "https://github.com/cankanoa/vhrharmonize"

[project.scripts]
vhr = "vhrharmonize.cli.main:main"

[project.entry-points."vhrharmonize.plugins"]
import_files = "vhrharmonize.plugins.import_files:ImportFiles"
restore_scenes = "vhrharmonize.plugins.restore_scenes:RestoreScenes"
file_source = "vhrharmonize.plugins.file_source:FileSource"
fetch_atmosphere = "vhrharmonize.plugins.fetch_atmosphere:FetchAtmosphere"
fetch_dem = "vhrharmonize.plugins.fetch_dem:FetchDEM"
atmospheric_correction = "vhrharmonize.plugins.atmospheric_correction:AtmosphericCorrection"
orthorectification = "vhrharmonize.plugins.orthorectification:Orthorectification"
pansharpen = "vhrharmonize.plugins.pansharpen:Pansharpen"
cloud_mask = "vhrharmonize.plugins.cloud_mask:CloudMask"
alignment = "vhrharmonize.plugins.alignment:Alignment"
seamline_metadata = "vhrharmonize.plugins.seamline_metadata:SeamlineMetadata"
joint_coregistration = "vhrharmonize.plugins.joint_coregistration:JointCoregistration"
global_regression = "vhrharmonize.plugins.global_regression:GlobalRegression"
local_block_adjustment = "vhrharmonize.plugins.local_block_adjustment:LocalBlockAdjustment"
align_rasters = "vhrharmonize.plugins.align_rasters:AlignRasters"
create_footprints = "vhrharmonize.plugins.create_footprints:CreateFootprints"
postprocess_footprints = "vhrharmonize.plugins.postprocess_footprints:PostprocessFootprints"
voronoi_center_seamline = "vhrharmonize.plugins.voronoi_center_seamline:VoronoiCenterSeamline"
weighted_seamline = "vhrharmonize.plugins.weighted_seamline:WeightedSeamline"
markov_triangles = "vhrharmonize.plugins.markov_triangles:MarkovTriangles"
mask_rasters = "vhrharmonize.plugins.mask_rasters:MaskRasters"
merge_rasters = "vhrharmonize.plugins.merge_rasters:MergeRasters"
merge_vectors = "vhrharmonize.plugins.merge_vectors:MergeVectors"
band_math = "vhrharmonize.plugins.band_math:BandMath"
create_cloud_mask_with_omnicloudmask = "vhrharmonize.plugins.create_cloud_mask_with_omnicloudmask:CreateCloudMaskWithOmnicloudmask"
process_raster_values_to_vector_polygons = "vhrharmonize.plugins.process_raster_values_to_vector_polygons:ProcessRasterValuesToVectorPolygons"
compute_overviews = "vhrharmonize.plugins.compute_overviews:ComputeOverviews"
search_paths = "vhrharmonize.plugins.search_paths:SearchPaths"
create_paths = "vhrharmonize.plugins.create_paths:CreatePaths"
match_paths = "vhrharmonize.plugins.match_paths:MatchPaths"
