moving_dir: /mnt/d/test_data/out/tiles
intensity_dir: /mnt/d/test_data/out/lidar_mean
output_dir: /mnt/d/test_data/out/elastix_reg_work
elastix_script: /home/milo/repos/elastix-wrapper/run_elastix_wv3_cbl_to_intensity.sh
moving_suffix: _final
intensity_dimension: Intensity
intensity_suffix: _mean
moving_band_index: 1
aligned_suffix: _aligned
recursive: false
overwrite: false
